Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  
  config.vm.define "machaq" do|machaq|
    machaq.vm.disk :disk , size: "10GB" , primary: true
    machaq.vm.hostname = "Server"
    machaq.vm.network "private_network", ip: "192.168.56.110", hostname: true
    machaq.vm.provider "virtualbox" do |vb|      
        vb.name = "machaq"
        vb.memory = "512"
        vb.cpus = "1"
    end
    config.vm.provision "shell", path:"scripts/server.sh" , binary:false
  end

  config.vm.define "machaq2" do|machaq2|
    machaq2.vm.disk :disk ,size: "10GB" , primary:true
    machaq2.vm.hostname = "ServerWorker"
    machaq2.vm.network "private_network", ip: "192.168.56.111", hostname: true
    machaq2.vm.provider "virtualbox" do|vb|
      vb.name = "machaq2"
      vb.memory = "512"
      vb.cpus = "1"
    end
    # config.vm.provision "shell" , path: "scripts/agent.sh"
  end
end