Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.box_version = "8.11.1"
  config.disksize..size = "10GB"
  config.vm.hostname = "Server"
  config.vm.network "public_network", ip: "192.168.56.110", hostname: true

  config.vm.define "machaq" do|machaq|
    config.vm.provider "virtualbox" do |vb|
          vb.name = "machaq"
          vb.memory = "512"
          vb.cpus = "1"
    end
  end
end